


apiVersion: v1
kind: Service
metadata:
  name: docx-to-pdf
spec:
  selector:
    app: docx-to-pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


# kubectl apply -f kubernetes/deployment.yaml
# kubectl apply -f kubernetes/service.yaml

